using System.Text;
using Microsoft.EntityFrameworkCore;
using VibeSwarm.Shared.Data;
using VibeSwarm.Shared.Validation;

namespace VibeSwarm.Web.Services;

public interface IProjectMemoryService
{
	Task<string?> PrepareMemoryFileAsync(Project? project, CancellationToken cancellationToken = default);
	Task SyncMemoryFromFileAsync(Guid projectId, string? memoryFilePath, CancellationToken cancellationToken = default);
}

public sealed class ProjectMemoryService(
	VibeSwarmDbContext dbContext,
	ILogger<ProjectMemoryService> logger) : IProjectMemoryService
{
	private const string MemoryDirectoryName = ".vibeswarm";
	private const string MemoryFileName = "project-memory.md";
	private static readonly UTF8Encoding Utf8NoBom = new(false);

	/// <summary>
	/// Tooling artifact directories and files written by VibeSwarm or its CLI agents that should
	/// never be committed to user repositories. Entries are added to .git/info/exclude (local,
	/// non-shared) so the user's .gitignore is never modified.
	/// </summary>
	private static readonly string[] ToolingExcludePatterns =
	[
		".vibeswarm/",    // VibeSwarm project memory and job prompt files
		".claude/",       // Claude Code project-level settings and session data
		".opencode/",     // OpenCode project-level config and session data
		".copilot/",      // GitHub Copilot workspace-level config and session data
		".aider*",        // Aider config, chat history, tags cache, and input history
		"tasks/todo.md",  // Claude Code task tracking files (auto-generated by agent workflow)
		"tasks/lessons.md", // Claude Code lessons tracking files (auto-generated by agent workflow)
	];

	/// <summary>
	/// Artifact files and directories that should be actively deleted from the working directory
	/// after a CLI agent finishes. These are non-code files that agents create for their own
	/// internal tracking and should not persist in the user's project.
	/// </summary>
	internal static readonly string[] ArtifactCleanupPatterns =
	[
		"tasks/todo.md",
		"tasks/lessons.md",
	];

	public async Task<string?> PrepareMemoryFileAsync(Project? project, CancellationToken cancellationToken = default)
	{
		if (project == null || string.IsNullOrWhiteSpace(project.WorkingPath))
		{
			return null;
		}

		var workingPath = project.WorkingPath.Trim();
		if (!Directory.Exists(workingPath))
		{
			logger.LogDebug("Skipping project memory file preparation because working path {WorkingPath} does not exist.", workingPath);
			return null;
		}

		var memoryDirectory = Path.Combine(workingPath, MemoryDirectoryName);
		Directory.CreateDirectory(memoryDirectory);
		await EnsureGitExcludeEntryAsync(workingPath, cancellationToken);

		var memoryFilePath = Path.Combine(memoryDirectory, MemoryFileName);
		var normalizedMemory = NormalizeMemory(project.Memory) ?? string.Empty;
		await File.WriteAllTextAsync(memoryFilePath, normalizedMemory, Utf8NoBom, cancellationToken);

		return memoryFilePath;
	}

	public async Task SyncMemoryFromFileAsync(Guid projectId, string? memoryFilePath, CancellationToken cancellationToken = default)
	{
		if (string.IsNullOrWhiteSpace(memoryFilePath) || !File.Exists(memoryFilePath))
		{
			return;
		}

		var updatedMemory = NormalizeMemory(await File.ReadAllTextAsync(memoryFilePath, cancellationToken));
		if (updatedMemory != null && updatedMemory.Length > ValidationLimits.ProjectMemoryMaxLength)
		{
			throw new InvalidOperationException($"Project memory exceeds the {ValidationLimits.ProjectMemoryMaxLength} character limit.");
		}

		var project = await dbContext.Projects.FirstOrDefaultAsync(project => project.Id == projectId, cancellationToken);
		if (project == null)
		{
			logger.LogWarning("Skipping project memory sync because project {ProjectId} no longer exists.", projectId);
			return;
		}

		var currentMemory = NormalizeMemory(project.Memory);
		if (string.Equals(currentMemory, updatedMemory, StringComparison.Ordinal))
		{
			return;
		}

		project.Memory = updatedMemory;
		project.UpdatedAt = DateTime.UtcNow;
		await dbContext.SaveChangesAsync(cancellationToken);
	}

	private static string? NormalizeMemory(string? memory)
	{
		if (string.IsNullOrWhiteSpace(memory))
		{
			return null;
		}

		return memory
			.Replace("\r\n", "\n", StringComparison.Ordinal)
			.Replace("\r", "\n", StringComparison.Ordinal)
			.Trim();
	}

	private static async Task EnsureGitExcludeEntryAsync(string workingPath, CancellationToken cancellationToken)
	{
		var gitDirectory = Path.Combine(workingPath, ".git");
		if (!Directory.Exists(gitDirectory))
		{
			return;
		}

		var gitInfoDirectory = Path.Combine(gitDirectory, "info");
		Directory.CreateDirectory(gitInfoDirectory);

		var excludeFilePath = Path.Combine(gitInfoDirectory, "exclude");

		var existingContent = File.Exists(excludeFilePath)
			? await File.ReadAllTextAsync(excludeFilePath, cancellationToken)
			: string.Empty;

		var existingLines = new HashSet<string>(
			existingContent.Split('\n', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries),
			StringComparer.Ordinal);

		var missingPatterns = ToolingExcludePatterns
			.Where(p => !existingLines.Contains(p))
			.ToList();

		if (missingPatterns.Count == 0)
		{
			return;
		}

		var builder = new StringBuilder(existingContent);
		if (builder.Length > 0 && !existingContent.EndsWith('\n'))
		{
			builder.AppendLine();
		}

		foreach (var pattern in missingPatterns)
		{
			builder.AppendLine(pattern);
		}

		await File.WriteAllTextAsync(excludeFilePath, builder.ToString(), Utf8NoBom, cancellationToken);
	}
}
