// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeSwarm.Shared.Data;

#nullable disable

namespace VibeSwarm.Shared.Data.Migrations
{
    [DbContext(typeof(VibeSwarmDbContext))]
    partial class VibeSwarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCycleMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultCycleReviewPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCycleSessionMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMaxCycles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibilities")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProviderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.AgentSkill", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("AgentSkills");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedIdeaImplementationPromptTemplate")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalErrorLogMaxEntries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(200);

                    b.Property<int>("CriticalErrorLogRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.Property<string>("DefaultProjectsDirectory")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableCommitAttribution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnablePromptStructuring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("GitHubToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeaExpansionPromptTemplate")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeaImplementationPromptTemplate")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InjectEfficiencyRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("InjectRepoMap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.CriticalErrorLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalDataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshAction")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TriggeredRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Source", "CreatedAt");

                    b.ToTable("CriticalErrorLogs");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpandedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpandedDescription")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpansionError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpansionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SortOrder");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.IdeaAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("IdeaAttachments");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.InferenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InferenceProviderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterSize")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantizationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InferenceProviderId", "ModelId", "TaskType")
                        .IsUnique();

                    b.ToTable("InferenceModels");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.InferenceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InferenceProviders");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.IterationLoop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCommit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPush")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedIterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentIdeaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InferenceModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InferenceProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIterationAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStopReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsageCheckResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxTotalCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextIterationAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentJobId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("IterationLoops");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveExecutionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachedFilesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BuildVerified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChangedFilesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandUsed")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsoleOutput")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentActivity")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCycle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CycleReviewPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleSessionMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DependsOnJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvironmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionCommandUsed")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailurePattern")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceFreshSession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GitChangeDeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitCheckpointBaseBranch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCheckpointBranch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GitCheckpointCapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCheckpointCommitHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCheckpointReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GitCheckpointStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitCommitBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitDiff")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalPrompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionChoices")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InteractionRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IterationLoopId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastResumeAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResumeFailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSwitchAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSwitchReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCycles")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxExecutionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingInteractionPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningCommandUsed")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanningGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningModelUsed")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningOutput")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlanningProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningReasoningEffortUsed")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlaywrightEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PullRequestCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoveryCheckpointAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryPrompt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResumeFromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledForUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionSummary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StallTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuccessPattern")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SwarmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobTemplateId");

                    b.HasIndex("PlanningProviderId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("SwarmId");

                    b.HasIndex("JobScheduleId", "ScheduledForUtc")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobChangeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BuildVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChangedFilesCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowUpIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitCommitBefore")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionSummary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "FollowUpIndex");

                    b.ToTable("JobChangeSets");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobExecutionStatistics", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.ToTable("JobExecutionStatistics");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolInput")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolOutput")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobId");

                    b.ToTable("JobMessages");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobPlanningStatistics", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.ToTable("JobPlanningStatistics");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobProviderAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "AttemptOrder");

                    b.ToTable("JobProviderAttempts");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HourUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdeaCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InferenceProviderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinuteUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("InferenceProviderId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("IsEnabled", "NextRunAtUtc");

                    b.HasIndex("ProjectId", "IsEnabled");

                    b.ToTable("JobSchedules");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobStatistics", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExecutionDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTokenEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalCostUsd")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.ToTable("JobStatistics");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CycleReviewPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleSessionMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GitChangeDeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalPrompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCycles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("JobTemplates");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutoCommitMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildCommand")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("BuildVerificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitSummaryInferenceModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommitSummaryInferenceProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTargetBranch")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableTeamSwarm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GitChangeDeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubRepository")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeaInferenceModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdeaInferenceProviderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IdeasAutoCommit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdeasProcessingActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdeasProcessingModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdeasProcessingProviderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memory")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlanningEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanningModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlanningProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptContext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoMap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RepoMapGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCommand")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProjectAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProjectId", "AgentId")
                        .IsUnique();

                    b.ToTable("ProjectAgents");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordCiphertext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameCiphertext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("ProjectEnvironments");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProjectProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProjectId", "Priority");

                    b.HasIndex("ProjectId", "ProviderId")
                        .IsUnique();

                    b.ToTable("ProjectProviders");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProviderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxContextTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetiresOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ModelId")
                        .IsUnique();

                    b.ToTable("ProviderModels");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProviderUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DetectedCurrentUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectedLimitReached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedLimitType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedLimitWindowsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DetectedMaxUsage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetectedResetTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PremiumRequestsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLimitMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("ProviderUsageRecords");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProviderUsageSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CliVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfiguredMaxUsage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveRateLimitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentUsage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLimitReached")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastJobStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRateLimitAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRateLimitMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LimitResetTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitWindowsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextExecutionAvailableAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalJobsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPremiumRequestsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VersionCheckedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("ProviderUsageSummaries");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedTools")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasScripts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguredLimitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfiguredUsageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultReasoningEffort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModelsRefreshAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxExecutionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StallTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Agent", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "DefaultProvider")
                        .WithMany()
                        .HasForeignKey("DefaultProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultProvider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.AgentSkill", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Agent", "Agent")
                        .WithMany("SkillLinks")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Data.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Idea", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany("Ideas")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.IdeaAttachment", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Idea", "Idea")
                        .WithMany("Attachments")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.InferenceModel", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.InferenceProvider", "InferenceProvider")
                        .WithMany("Models")
                        .HasForeignKey("InferenceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InferenceProvider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.IterationLoop", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "CurrentJob")
                        .WithMany()
                        .HasForeignKey("CurrentJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentJob");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Job", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.JobSchedule", "JobSchedule")
                        .WithMany("Jobs")
                        .HasForeignKey("JobScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.JobTemplate", "JobTemplate")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "PlanningProvider")
                        .WithMany()
                        .HasForeignKey("PlanningProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("JobSchedule");

                    b.Navigation("JobTemplate");

                    b.Navigation("PlanningProvider");

                    b.Navigation("Project");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobChangeSet", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithMany("ChangeSets")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobExecutionStatistics", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithOne("ExecutionStatistics")
                        .HasForeignKey("VibeSwarm.Shared.Data.JobExecutionStatistics", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobMessage", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithMany("Messages")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobPlanningStatistics", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithOne("PlanningStatistics")
                        .HasForeignKey("VibeSwarm.Shared.Data.JobPlanningStatistics", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobProviderAttempt", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithMany("ProviderAttempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobSchedule", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.InferenceProvider", "InferenceProvider")
                        .WithMany()
                        .HasForeignKey("InferenceProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("InferenceProvider");

                    b.Navigation("Project");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobStatistics", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithOne("Statistics")
                        .HasForeignKey("VibeSwarm.Shared.Data.JobStatistics", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobTemplate", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProjectAgent", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Agent", "Agent")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany("AgentAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Project");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProjectEnvironment", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProjectProvider", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Project", "Project")
                        .WithMany("ProviderSelections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProviderModel", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany("AvailableModels")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProviderUsageRecord", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Data.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.ProviderUsageSummary", b =>
                {
                    b.HasOne("VibeSwarm.Shared.Providers.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Agent", b =>
                {
                    b.Navigation("ProjectAssignments");

                    b.Navigation("SkillLinks");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Idea", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.InferenceProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Job", b =>
                {
                    b.Navigation("ChangeSets");

                    b.Navigation("ExecutionStatistics");

                    b.Navigation("Messages");

                    b.Navigation("PlanningStatistics");

                    b.Navigation("ProviderAttempts");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobSchedule", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.JobTemplate", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Data.Project", b =>
                {
                    b.Navigation("AgentAssignments");

                    b.Navigation("Environments");

                    b.Navigation("Ideas");

                    b.Navigation("Jobs");

                    b.Navigation("ProviderSelections");
                });

            modelBuilder.Entity("VibeSwarm.Shared.Providers.Provider", b =>
                {
                    b.Navigation("AvailableModels");
                });
#pragma warning restore 612, 618
        }
    }
}
